### ISSUE TITLE
Moving over some plugins to the community

### ISSUE THREAD

**Issue by rejas** [gulp-community/meta#10]
Hi since my gulp days some plugins have not gotten some love, so I would transfer them over here if you want:
- https://github.com/rejas/gulp-json-editor
- https://github.com/rejas/gulp-favicons

Also as a co maintainer I proposed to move this here too:
- https://github.com/ben-eb/gulp-svgmin/pull/129

What do you think?

**Comment by phated** [comment]
Sure!

**Comment by rejas** [comment]
Who should I transfer it to then? gulp-community?

**Comment by phated** [comment]
Just transfer them to me and I'll take care of it.

**Comment by phated** [comment]
Please remember that you have to add me (https://www.npmjs.com/~phated) as an npm owner otherwise having the repo isn't valuable!

**Comment by rejas** [comment]
Added you as a maintainer...

**Comment by phated** [comment]
Thanks! I'll close this out.
