### ISSUE TITLE
Need an additional maintainer?

### ISSUE THREAD

**Issue by stamminator** [gulp-community/meta#11]
Hi folks,

I've tried reaching out via `team@gulpjs.com` a couple times in July, but I haven't heard back. I'll copy my email below.

___

I've been a Gulp user since about 2016. As a .NET web developer, it fills a great niche of being an IDE-agnostic solution to compiling, bundling, and minifying the front-end assets for my projects. I've had the impression for a few years now that the Gulp ecosystem is dying, but when I look at the alternatives the web development community has embraced (Webpack, Parcel, and Rollup), I find myself confused as to why solutions that seem overly complicated and have a high learning curve have supplanted ones like Gulp which "just work". I think too many JS developers are addicted to complexity for its own sake.

I was surprised then to find today that there's a Gulp 5! I had to manually check npm and then do a web search for "gulp 5" before seeing anything about it. It looks like you guys have done an immense amount of work to clean up and modernize the tooling, and firstly, I want to say thank you! I've just become a sponsor (just $5 a month, but I may increase that) and would love to see it succeed.

I'd also like to offer to become a maintainer or contribute my time in some fashion that would help Gulp 5 and the various top plugins take hold. It looks to me like the key areas of need are:

- Stabilizing the v5 release
- Relaunching gulpjs.com to hype the shit out of Gulp 5
- Clearly communicating to developers what use cases justify choosing Gulp over the alternatives
- Clearly communicating which packages are run by the Gulp team, which are not, and which ones have been successfully validated against Gulp 5
- Figure out what needs to happen with https://github.com/gulp-community. It's a ghost town.

Please let me know if there's any way I can contribute. I want Gulp 5 to be a solid tool that I can enthusiastically recommend.

**Comment by stamminator** [comment]
@yocontra @phated @sttk I'm noticing that some comments on https://github.com/gulpjs/gulp which draw attention to the out-of-date documentation and the development woes that are arising from that are being hidden by moderators. Perhaps a better way to handle that would be to give an update on the status. I understand this is an open-source project that you guys manage in your free time in addition to life's other commitments. At the same time, the concerns being raised are valid. In light of those concerns, the comment moderation and infrequent, inconsistent communication paint a discouraging picture, and it's not a good look.

I'm not offering criticism without solutions. I'm willing to put some time and money into helping get things on track. If you haven't seen this post or my emails (jacobstamm@outlook.com) until now, please give them a look.

**Comment by phated** [comment]
The way to get involved is to get involved. We're not looking to onboard any maintainers right now.

**Comment by stamminator** [comment]
@phated Like anyone else, I value my time and would prefer to put my time and effort into projects whose maintainers have the buy-in needed to make the project succeed. Who wants to invest in something just to watch it slowly die due to mismanagement?

**Comment by phated** [comment]
Coming into a project and asking to become a maintainer without showing any effort whatsoever sure sounds like some Jia Tan-level manipulation.

I'm going to lock this thread, but feel free to actually submit PRs that can be reviewed if you have true interest in helping out.
