### ISSUE TITLE
moving gulp-header/footer to community

### ISSUE THREAD

**Issue by tracker1** [gulp-community/meta#3]
Curious if you'd be open to moving gulp-header and footer to the community repo?  I really haven't done much with either in a long while, but they're still relatively popular.

**Comment by yocontra** [comment]
@tracker1 Yeah that seems like a good idea, you can transfer the repos to the org and I can take care of the rest (updating, etc.)

**Comment by tracker1** [comment]
It's saying "you don't have permission to create repositories on gulp-community"  if you can grant access temporarily, can get them transfered... can then get the npm ownership moved over...

**Comment by tracker1** [comment]
I'd message you on twitter, but you aren't following.

**Comment by tracker1** [comment]
@contra added you and @phated to npm for the two packages.

**Comment by phated** [comment]
@tracker1 invited you to this org. Members can "create" repos so you can transfer once accepted. Welcome!

**Comment by yocontra** [comment]
@tracker1 Sorry, I wiped my twitter acc a few years ago and don't use it anymore. Got the emails about the permissions though.
