### ISSUE TITLE
moving/gulp-terser-js to community

### ISSUE THREAD

**Issue by A-312** [gulp-community/meta#4]
Hi, I want to know if [gulp-terser-js](https://www.npmjs.com/package/gulp-terser-js) ([Github Page](https://github.com/A-312/gulp-terser-js)) can join your community ? Is a stable project since August 2019

**Comment by phated** [comment]
@A-312 Sure! I'll send you an invite shortly

**Comment by phated** [comment]
Invite sent. Once you join, you should be able to transfer the repository and close this issue! Happy to have you onboard 😄

**Comment by A-312** [comment]
Done thanks :)
