### ISSUE TITLE
Grant travis-ci.com

### ISSUE THREAD

**Issue by A-312** [gulp-community/meta#5]
For my test I use travis app: 

Can we add this one ?

https://github.com/settings/connections/applications/88c5b97de2dbfc50f3ac

![image](https://user-images.githubusercontent.com/18501150/81438240-b658f480-916c-11ea-9ffc-eb0c6d823cda.png)

**Comment by A-312** [comment]
https://travis-ci.com/gulp-community/gulp-terser-js

**Comment by phated** [comment]
Approved! On gulpjs, we are switching everything to GitHub Actions, so we should consider making the same changes on these projects.

**Comment by A-312** [comment]
Seem like I need a second request for travis (I choose only gulp-terser-js)

> A request to install Travis CI has been submitted on the @gulp-community account.

**Comment by phated** [comment]
Approved

**Comment by A-312** [comment]
Seem good but I don't get the badge/cheking in my PR : https://github.com/gulp-community/gulp-terser-js/pull/21 🤔 

I can't acces to settings of https://github.com/gulp-community/gulp-terser-js/pull/21 maybe something we should enable ?

**Comment by phated** [comment]
@A-312 it's live https://travis-ci.com/github/gulp-community/gulp-terser-js 🤷

**Comment by A-312** [comment]
Also here : https://github.com/gulp-community/gulp-terser-js/settings/installations

![image](https://user-images.githubusercontent.com/18501150/81441370-f078c500-9171-11ea-9f29-90b2f6e25d19.png)

**Comment by A-312** [comment]
> @A-312 it's live https://travis-ci.com/github/gulp-community/gulp-terser-js 🤷

I saw but if it was perfectly add, we should get: 

![image](https://user-images.githubusercontent.com/18501150/81441617-5ebd8780-9172-11ea-8e4b-83db2091120a.png)

EDIT : [OK](https://github.com/gulp-community/gulp-terser-js/pull/21) :)
