### ISSUE TITLE
Grant Coveralls

### ISSUE THREAD

**Issue by A-312** [gulp-community/meta#6]
I use Coveralls too for my repo : 

https://github.com/settings/connections/applications/ad4c01c89848a307e228

![image](https://user-images.githubusercontent.com/18501150/81438428-0b950600-916d-11ea-9557-a70802c61c6b.png)

**Comment by A-312** [comment]
https://coveralls.io/r/gulp-community/gulp-terser-js?branch=master

**Comment by phated** [comment]
Approved!

**Comment by A-312** [comment]
Sorry, seem not to be the good one for organization: 

https://github.com/settings/connections/applications/5b064d049aaeb3438e8e

![image](https://user-images.githubusercontent.com/18501150/81440555-8d3a6300-9170-11ea-928e-5ce358b8b7b2.png)

**Comment by phated** [comment]
@A-312 what's the difference between Coveralls and Coveralls Pro? I also noticed that we had Travis but not Travis Pro.

I hope you don't get charged for these.

**Comment by A-312** [comment]
> @A-312 what's the difference between Coveralls and Coveralls Pro? I also noticed that we had Travis but not Travis Pro.
> 
> I hope you don't get charged for these.

In the feature is the same, but website can be different like travis-ci.org and travis-ci.com. https://github.com/marketplace/coveralls

Free for opensource : 
![image](https://user-images.githubusercontent.com/18501150/81441145-8829e380-9171-11ea-9624-b92b99120c59.png)

**Comment by A-312** [comment]
Also, I never paid for my public organization: 

![image](https://user-images.githubusercontent.com/18501150/81442200-75181300-9173-11ea-8b5e-4ee7805e0cdf.png)
